Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -7,5 +7,11 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Run a one-line script
+      - name: Greeting
+        run: echo "Hey, world!"
+
+      - name: Simulate an error
+        run: echo "About to fail" ; exit 1
+
+      - name: Another greeting
         run: echo "Hello, world!"
